USE ROLE ACCOUNTADMIN;
USE DATABASE CUSTOMER_DEMOS;
USE SCHEMA YMC;
USE WAREHOUSE YMC_WH;

-- =============================================================================
-- V_IT_TICKET_DASHBOARD
-- =============================================================================
CREATE OR REPLACE VIEW V_IT_TICKET_DASHBOARD AS
SELECT
    t.TICKET_ID,
    t.TICKET_NUMBER,
    t.SUBJECT,
    t.CATEGORY,
    t.SUBCATEGORY,
    t.PRIORITY,
    t.STATUS,
    t.CREATED_DATE,
    t.RESOLVED_DATE,
    t.RESOLUTION_HOURS,
    t.SATISFACTION_SCORE,
    t.ASSIGNED_TECHNICIAN,
    b.BRANCH_NAME,
    b.CITY,
    b.REGION,
    e.FIRST_NAME || ' ' || e.LAST_NAME AS REQUESTOR_NAME,
    e.DEPARTMENT_ID,
    d.DEPARTMENT_NAME,
    CASE WHEN t.STATUS IN ('Open', 'In Progress', 'Awaiting User') THEN TRUE ELSE FALSE END AS IS_OPEN,
    CASE
        WHEN t.PRIORITY = 'P1' AND t.RESOLUTION_HOURS > 4 THEN TRUE
        WHEN t.PRIORITY = 'P2' AND t.RESOLUTION_HOURS > 24 THEN TRUE
        WHEN t.PRIORITY = 'P3' AND t.RESOLUTION_HOURS > 48 THEN TRUE
        WHEN t.PRIORITY = 'P4' AND t.RESOLUTION_HOURS > 72 THEN TRUE
        ELSE FALSE
    END AS SLA_BREACHED
FROM IT_TICKETS t
JOIN BRANCHES b ON t.BRANCH_ID = b.BRANCH_ID
JOIN EMPLOYEES e ON t.EMPLOYEE_ID = e.EMPLOYEE_ID
JOIN DEPARTMENTS d ON e.DEPARTMENT_ID = d.DEPARTMENT_ID;

-- =============================================================================
-- V_MEMBERSHIP_DASHBOARD
-- =============================================================================
CREATE OR REPLACE VIEW V_MEMBERSHIP_DASHBOARD AS
SELECT
    m.MEMBER_ID,
    m.FIRST_NAME || ' ' || m.LAST_NAME AS MEMBER_NAME,
    m.STATUS,
    m.JOIN_DATE,
    m.AGE_GROUP,
    m.GENDER,
    b.BRANCH_NAME,
    b.CITY,
    b.REGION,
    mt.TYPE_NAME AS MEMBERSHIP_TYPE,
    mt.CATEGORY AS MEMBERSHIP_CATEGORY,
    mt.MONTHLY_FEE,
    mt.ANNUAL_FEE,
    DATE_TRUNC('month', m.JOIN_DATE) AS JOIN_MONTH,
    DATEDIFF('month', m.JOIN_DATE, CURRENT_DATE()) AS TENURE_MONTHS
FROM MEMBERS m
JOIN BRANCHES b ON m.BRANCH_ID = b.BRANCH_ID
JOIN MEMBERSHIP_TYPES mt ON m.MEMBERSHIP_TYPE_ID = mt.MEMBERSHIP_TYPE_ID;

-- =============================================================================
-- V_CHILDCARE_CAPACITY
-- =============================================================================
CREATE OR REPLACE VIEW V_CHILDCARE_CAPACITY AS
SELECT
    cp.PROGRAM_ID,
    cp.PROGRAM_NAME,
    cp.PROGRAM_TYPE,
    cp.CAPACITY,
    cp.CURRENT_ENROLLMENT,
    ROUND(cp.CURRENT_ENROLLMENT * 100.0 / NULLIF(cp.CAPACITY, 0), 1) AS UTILIZATION_PCT,
    cp.CAPACITY - cp.CURRENT_ENROLLMENT AS AVAILABLE_SPOTS,
    cp.AGE_MIN_MONTHS,
    cp.AGE_MAX_MONTHS,
    cp.MONTHLY_FEE,
    cp.SUBSIDY_ACCEPTED,
    cp.STATUS AS PROGRAM_STATUS,
    b.BRANCH_NAME,
    b.CITY,
    b.REGION,
    COUNT(ce.ENROLLMENT_ID) AS TOTAL_ENROLLMENTS,
    SUM(CASE WHEN ce.STATUS = 'Active' THEN 1 ELSE 0 END) AS ACTIVE_ENROLLMENTS,
    SUM(CASE WHEN ce.SUBSIDY_ELIGIBLE = TRUE THEN 1 ELSE 0 END) AS SUBSIDY_ENROLLMENTS,
    SUM(ce.SUBSIDY_AMOUNT) AS TOTAL_SUBSIDY_AMOUNT
FROM CHILDCARE_PROGRAMS cp
JOIN BRANCHES b ON cp.BRANCH_ID = b.BRANCH_ID
LEFT JOIN CHILDCARE_ENROLLMENTS ce ON cp.PROGRAM_ID = ce.PROGRAM_ID
GROUP BY
    cp.PROGRAM_ID, cp.PROGRAM_NAME, cp.PROGRAM_TYPE, cp.CAPACITY,
    cp.CURRENT_ENROLLMENT, cp.AGE_MIN_MONTHS, cp.AGE_MAX_MONTHS,
    cp.MONTHLY_FEE, cp.SUBSIDY_ACCEPTED, cp.STATUS,
    b.BRANCH_NAME, b.CITY, b.REGION;

-- =============================================================================
-- V_EMPLOYEE_DASHBOARD
-- =============================================================================
CREATE OR REPLACE VIEW V_EMPLOYEE_DASHBOARD AS
SELECT
    e.EMPLOYEE_ID,
    e.FIRST_NAME || ' ' || e.LAST_NAME AS EMPLOYEE_NAME,
    e.POSITION_TITLE,
    e.EMPLOYMENT_TYPE,
    e.HIRE_DATE,
    e.STATUS,
    e.HOURLY_RATE,
    e.IS_ACTIVE,
    d.DEPARTMENT_NAME,
    d.DIVISION,
    b.BRANCH_NAME,
    b.CITY,
    b.REGION,
    DATEDIFF('day', e.HIRE_DATE, CURRENT_DATE()) AS TENURE_DAYS,
    CASE WHEN e.HIRE_DATE >= DATEADD('day', -90, CURRENT_DATE()) THEN TRUE ELSE FALSE END AS IS_NEW_HIRE,
    COUNT(ot.TASK_ID) AS TOTAL_ONBOARDING_TASKS,
    SUM(CASE WHEN ot.STATUS = 'Completed' THEN 1 ELSE 0 END) AS COMPLETED_TASKS,
    ROUND(
        SUM(CASE WHEN ot.STATUS = 'Completed' THEN 1 ELSE 0 END) * 100.0
        / NULLIF(COUNT(ot.TASK_ID), 0), 1
    ) AS ONBOARDING_COMPLETION_PCT
FROM EMPLOYEES e
JOIN DEPARTMENTS d ON e.DEPARTMENT_ID = d.DEPARTMENT_ID
JOIN BRANCHES b ON e.BRANCH_ID = b.BRANCH_ID
LEFT JOIN ONBOARDING_TASKS ot ON e.EMPLOYEE_ID = ot.EMPLOYEE_ID
GROUP BY
    e.EMPLOYEE_ID, e.FIRST_NAME, e.LAST_NAME, e.POSITION_TITLE,
    e.EMPLOYMENT_TYPE, e.HIRE_DATE, e.STATUS, e.HOURLY_RATE, e.IS_ACTIVE,
    d.DEPARTMENT_NAME, d.DIVISION, b.BRANCH_NAME, b.CITY, b.REGION;

-- =============================================================================
-- V_LEAD_CONVERSION
-- =============================================================================
CREATE OR REPLACE VIEW V_LEAD_CONVERSION AS
SELECT
    l.LEAD_ID,
    l.FIRST_NAME || ' ' || l.LAST_NAME AS LEAD_NAME,
    l.SOURCE,
    l.STATUS,
    l.CREATED_DATE,
    l.IS_CONVERTED,
    l.CONVERTED_DATE,
    b.BRANCH_NAME,
    b.CITY,
    b.REGION,
    DATE_TRUNC('month', l.CREATED_DATE) AS CREATED_MONTH,
    CASE WHEN l.IS_CONVERTED = TRUE
         THEN DATEDIFF('day', l.CREATED_DATE, l.CONVERTED_DATE)
         ELSE NULL
    END AS DAYS_TO_CONVERT
FROM LEADS l
JOIN BRANCHES b ON l.BRANCH_ID = b.BRANCH_ID;
