USE ROLE ACCOUNTADMIN;
USE DATABASE CUSTOMER_DEMOS;
USE SCHEMA YMC;
USE WAREHOUSE YMC_WH;

-- =============================================================================
-- PARENT TABLES (standalone, no FKs)
-- =============================================================================

CREATE OR REPLACE TABLE BRANCHES (
    BRANCH_ID INT AUTOINCREMENT START 1 INCREMENT 1,
    BRANCH_NAME VARCHAR(100) NOT NULL,
    CITY VARCHAR(50) NOT NULL,
    REGION VARCHAR(50) NOT NULL,
    DIRECTOR_NAME VARCHAR(100),
    PHONE VARCHAR(20),
    ADDRESS VARCHAR(200),
    PRIMARY KEY (BRANCH_ID)
);

CREATE OR REPLACE TABLE MEMBERSHIP_TYPES (
    MEMBERSHIP_TYPE_ID INT AUTOINCREMENT START 1 INCREMENT 1,
    TYPE_NAME VARCHAR(50) NOT NULL,
    CATEGORY VARCHAR(30) NOT NULL,
    MONTHLY_FEE NUMBER(8,2),
    ANNUAL_FEE NUMBER(8,2),
    PRIMARY KEY (MEMBERSHIP_TYPE_ID)
);

CREATE OR REPLACE TABLE DEPARTMENTS (
    DEPARTMENT_ID INT AUTOINCREMENT START 1 INCREMENT 1,
    DEPARTMENT_NAME VARCHAR(100) NOT NULL,
    DIVISION VARCHAR(50) NOT NULL,
    COST_CENTER VARCHAR(20),
    PRIMARY KEY (DEPARTMENT_ID)
);

-- =============================================================================
-- LEVEL 2 TABLES (FK to parent tables)
-- =============================================================================

CREATE OR REPLACE TABLE EMPLOYEES (
    EMPLOYEE_ID INT AUTOINCREMENT START 1 INCREMENT 1,
    FIRST_NAME VARCHAR(50) NOT NULL,
    LAST_NAME VARCHAR(50) NOT NULL,
    EMAIL VARCHAR(150),
    DEPARTMENT_ID INT NOT NULL,
    BRANCH_ID INT NOT NULL,
    POSITION_TITLE VARCHAR(100),
    EMPLOYMENT_TYPE VARCHAR(20) NOT NULL,
    HIRE_DATE DATE NOT NULL,
    STATUS VARCHAR(20) DEFAULT 'Active',
    HOURLY_RATE NUMBER(8,2),
    MANAGER_ID INT,
    IS_ACTIVE BOOLEAN DEFAULT TRUE,
    PRIMARY KEY (EMPLOYEE_ID),
    FOREIGN KEY (DEPARTMENT_ID) REFERENCES DEPARTMENTS(DEPARTMENT_ID),
    FOREIGN KEY (BRANCH_ID) REFERENCES BRANCHES(BRANCH_ID)
);

CREATE OR REPLACE TABLE MEMBERS (
    MEMBER_ID INT AUTOINCREMENT START 1 INCREMENT 1,
    FIRST_NAME VARCHAR(50) NOT NULL,
    LAST_NAME VARCHAR(50) NOT NULL,
    EMAIL VARCHAR(150),
    BRANCH_ID INT NOT NULL,
    MEMBERSHIP_TYPE_ID INT NOT NULL,
    JOIN_DATE DATE NOT NULL,
    STATUS VARCHAR(20) DEFAULT 'Active',
    AGE_GROUP VARCHAR(20),
    GENDER VARCHAR(20),
    PRIMARY KEY (MEMBER_ID),
    FOREIGN KEY (BRANCH_ID) REFERENCES BRANCHES(BRANCH_ID),
    FOREIGN KEY (MEMBERSHIP_TYPE_ID) REFERENCES MEMBERSHIP_TYPES(MEMBERSHIP_TYPE_ID)
);

CREATE OR REPLACE TABLE LEADS (
    LEAD_ID INT AUTOINCREMENT START 1 INCREMENT 1,
    FIRST_NAME VARCHAR(50) NOT NULL,
    LAST_NAME VARCHAR(50) NOT NULL,
    EMAIL VARCHAR(150),
    SOURCE VARCHAR(50) NOT NULL,
    BRANCH_ID INT NOT NULL,
    CREATED_DATE DATE NOT NULL,
    STATUS VARCHAR(30) DEFAULT 'New',
    IS_CONVERTED BOOLEAN DEFAULT FALSE,
    CONVERTED_DATE DATE,
    PRIMARY KEY (LEAD_ID),
    FOREIGN KEY (BRANCH_ID) REFERENCES BRANCHES(BRANCH_ID)
);

CREATE OR REPLACE TABLE CHILDCARE_PROGRAMS (
    PROGRAM_ID INT AUTOINCREMENT START 1 INCREMENT 1,
    PROGRAM_NAME VARCHAR(150) NOT NULL,
    PROGRAM_TYPE VARCHAR(50) NOT NULL,
    BRANCH_ID INT NOT NULL,
    CAPACITY INT NOT NULL,
    CURRENT_ENROLLMENT INT DEFAULT 0,
    AGE_MIN_MONTHS INT,
    AGE_MAX_MONTHS INT,
    MONTHLY_FEE NUMBER(8,2),
    SUBSIDY_ACCEPTED BOOLEAN DEFAULT TRUE,
    STATUS VARCHAR(20) DEFAULT 'Active',
    PRIMARY KEY (PROGRAM_ID),
    FOREIGN KEY (BRANCH_ID) REFERENCES BRANCHES(BRANCH_ID)
);

-- =============================================================================
-- LEVEL 3 TABLES (FK to level 2 tables)
-- =============================================================================

CREATE OR REPLACE TABLE CHILDCARE_ENROLLMENTS (
    ENROLLMENT_ID INT AUTOINCREMENT START 1 INCREMENT 1,
    PROGRAM_ID INT NOT NULL,
    CHILD_FIRST_NAME VARCHAR(50) NOT NULL,
    CHILD_LAST_NAME VARCHAR(50) NOT NULL,
    PARENT_NAME VARCHAR(100),
    PARENT_EMAIL VARCHAR(150),
    ENROLLMENT_DATE DATE NOT NULL,
    STATUS VARCHAR(20) DEFAULT 'Active',
    SUBSIDY_ELIGIBLE BOOLEAN DEFAULT FALSE,
    SUBSIDY_AMOUNT NUMBER(8,2) DEFAULT 0,
    PRIMARY KEY (ENROLLMENT_ID),
    FOREIGN KEY (PROGRAM_ID) REFERENCES CHILDCARE_PROGRAMS(PROGRAM_ID)
);

CREATE OR REPLACE TABLE IT_TICKETS (
    TICKET_ID INT AUTOINCREMENT START 1 INCREMENT 1,
    TICKET_NUMBER VARCHAR(20) NOT NULL,
    SUBJECT VARCHAR(200) NOT NULL,
    CATEGORY VARCHAR(50) NOT NULL,
    SUBCATEGORY VARCHAR(50),
    PRIORITY VARCHAR(10) NOT NULL,
    STATUS VARCHAR(20) DEFAULT 'Open',
    CREATED_DATE TIMESTAMP_NTZ NOT NULL,
    RESOLVED_DATE TIMESTAMP_NTZ,
    EMPLOYEE_ID INT NOT NULL,
    BRANCH_ID INT NOT NULL,
    ASSIGNED_TECHNICIAN VARCHAR(100),
    RESOLUTION_HOURS NUMBER(8,2),
    SATISFACTION_SCORE INT,
    PRIMARY KEY (TICKET_ID),
    FOREIGN KEY (EMPLOYEE_ID) REFERENCES EMPLOYEES(EMPLOYEE_ID),
    FOREIGN KEY (BRANCH_ID) REFERENCES BRANCHES(BRANCH_ID)
);

CREATE OR REPLACE TABLE ONBOARDING_TASKS (
    TASK_ID INT AUTOINCREMENT START 1 INCREMENT 1,
    EMPLOYEE_ID INT NOT NULL,
    TASK_NAME VARCHAR(200) NOT NULL,
    CATEGORY VARCHAR(50) NOT NULL,
    DUE_DATE DATE NOT NULL,
    COMPLETED_DATE DATE,
    STATUS VARCHAR(20) DEFAULT 'Pending',
    PRIMARY KEY (TASK_ID),
    FOREIGN KEY (EMPLOYEE_ID) REFERENCES EMPLOYEES(EMPLOYEE_ID)
);
